{"last_activity_date": 1477838435, "owner": {"display_name": "Cahit Y\u0131ld\u0131r\u0131m", "reputation": 99, "profile_image": "https://graph.facebook.com/1704470243118587/picture?type=large", "user_id": 5650922, "user_type": "registered", "accept_rate": 48, "link": "http://stackoverflow.com/users/5650922/cahit-y%c4%b1ld%c4%b1r%c4%b1m"}, "is_answered": false, "answer_count": 1, "creation_date": 1453469630, "score": 0, "title": "Twain Module Raise an Exception : twain.excTWCC_SEQERROR", "tags": ["python", "twain"], "view_count": 75, "question_id": 34947935, "link": "http://stackoverflow.com/questions/34947935/twain-module-raise-an-exception-twain-exctwcc-seqerror"}