{"is_answered": false, "view_count": 115, "tags": ["python", "sqlite", "pandas"], "last_activity_date": 1468931364, "answer_count": 0, "creation_date": 1468931364, "score": 0, "link": "http://stackoverflow.com/questions/38458635/python-sqlite-error-attempt-to-write-a-readonly-database", "owner": {"user_id": 4559679, "profile_image": "https://www.gravatar.com/avatar/ae846f14231588bc18f828da347a2c7e?s=128&d=identicon&r=PG&f=1", "user_type": "registered", "reputation": 53, "link": "http://stackoverflow.com/users/4559679/nonegiven72", "accept_rate": 23, "display_name": "nonegiven72"}, "title": "Python SQLite error: &quot;attempt to write a readonly database&quot;", "question_id": 38458635}