{"is_answered": false, "view_count": 54, "tags": ["python", "sql", "pandas"], "last_activity_date": 1470948890, "answer_count": 0, "creation_date": 1470912077, "score": 0, "link": "http://stackoverflow.com/questions/38894087/geting-pandasql-sqldf-pandasqlexception-sqlite3-operationalerror-no-such-tabl", "owner": {"user_id": 4874506, "profile_image": "https://www.gravatar.com/avatar/86446152b5aa8d08c806fd630a838624?s=128&d=identicon&r=PG&f=1", "user_type": "registered", "reputation": 23, "link": "http://stackoverflow.com/users/4874506/vedad", "accept_rate": 70, "display_name": "Vedad"}, "title": "Geting pandasql.sqldf.PandaSQLException: (sqlite3.OperationalError) no such table: by using a query on a csv", "last_edit_date": 1470948890, "question_id": 38894087}