{"is_answered": true, "view_count": 68, "tags": ["python", "python-2.7", "python-3.x", "pandas"], "last_activity_date": 1471469509, "answer_count": 1, "creation_date": 1470999055, "score": 0, "link": "http://stackoverflow.com/questions/38916188/pandas-start-generating-run-time-warning-error-and-require-restart", "owner": {"user_id": 6244166, "profile_image": "https://www.gravatar.com/avatar/0733a365cf3e3ba71910508864b6ae7a?s=128&d=identicon&r=PG&f=1", "user_type": "registered", "reputation": 101, "link": "http://stackoverflow.com/users/6244166/user110244", "accept_rate": 8, "display_name": "user110244"}, "title": "Pandas start generating Run-time warning error and require restart", "last_edit_date": 1470999371, "question_id": 38916188}