{"owner": {"display_name": "DerWeh", "reputation": 93, "profile_image": "https://www.gravatar.com/avatar/0f18b864757cb0381b5a47dc01d0ea5e?s=128&d=identicon&r=PG&f=1", "user_id": 6950750, "user_type": "registered", "link": "http://stackoverflow.com/users/6950750/derweh"}, "link": "http://stackoverflow.com/questions/40200619/pythonic-exception-handling-only-catching-specific-errno", "tags": ["python", "error-handling", "errno"], "creation_date": 1477207918, "score": 2, "last_edit_date": 1477342330, "is_answered": false, "view_count": 42, "last_activity_date": 1477343985, "question_id": 40200619, "answer_count": 2, "title": "Pythonic exception handling: only catching specific errno"}