{"owner": {"display_name": "Osama Rasheed", "reputation": 28, "profile_image": "https://www.gravatar.com/avatar/5da244e45154c086efe67ac014f04d4b?s=128&d=identicon&r=PG", "user_id": 2291697, "user_type": "registered", "accept_rate": 40, "link": "http://stackoverflow.com/users/2291697/osama-rasheed"}, "link": "http://stackoverflow.com/questions/40206369/python-ssl-socket-certificate-verify-failed-error", "tags": ["python", "sockets", "ssl", "pyopenssl", "mutual-authentication"], "creation_date": 1477246986, "score": 1, "last_edit_date": 1477262076, "is_answered": true, "view_count": 18, "last_activity_date": 1477262076, "question_id": 40206369, "accepted_answer_id": 40206826, "answer_count": 1, "title": "Python SSL Socket Certificate Verify Failed Error"}