{"last_activity_date": 1477285089, "owner": {"display_name": "Frits Verstraten", "reputation": 144, "profile_image": "https://www.gravatar.com/avatar/b02883ae7e82b518cef831ab5bacb10d?s=128&d=identicon&r=PG&f=1", "user_id": 6039787, "user_type": "registered", "accept_rate": 55, "link": "http://stackoverflow.com/users/6039787/frits-verstraten"}, "is_answered": false, "answer_count": 0, "creation_date": 1477285089, "score": 0, "title": "Using the nltk.lemmatizer throws error", "tags": ["python"], "view_count": 6, "question_id": 40210969, "link": "http://stackoverflow.com/questions/40210969/using-the-nltk-lemmatizer-throws-error"}