{"last_activity_date": 1477417254, "owner": {"display_name": "Brian Bruggeman", "reputation": 1111, "profile_image": "https://www.gravatar.com/avatar/8d14e043d3c1f08e23d0a6fbbed1be3e?s=128&d=identicon&r=PG", "user_id": 631199, "user_type": "registered", "accept_rate": 57, "link": "http://stackoverflow.com/users/631199/brian-bruggeman"}, "is_answered": false, "answer_count": 0, "creation_date": 1477417254, "score": 0, "title": "How to handle a process exception using Circus", "tags": ["python", "monitoring", "circusd"], "view_count": 7, "question_id": 40246324, "link": "http://stackoverflow.com/questions/40246324/how-to-handle-a-process-exception-using-circus"}