{"last_activity_date": 1477400516, "owner": {"display_name": "user3017691", "reputation": 28, "profile_image": "https://www.gravatar.com/avatar/0eb62c3e6264f6e0cb9a80c9e4872e70?s=128&d=identicon&r=PG&f=1", "user_id": 3017691, "user_type": "registered", "accept_rate": 20, "link": "http://stackoverflow.com/users/3017691/user3017691"}, "is_answered": false, "answer_count": 0, "creation_date": 1477400516, "score": 0, "title": "python mechanize basic auth fails", "tags": ["python", "mechanize", "basic-authentication"], "view_count": 8, "question_id": 40240720, "link": "http://stackoverflow.com/questions/40240720/python-mechanize-basic-auth-fails"}