{"owner": {"display_name": "Jeyakeethan Geethan", "reputation": 6, "profile_image": "https://lh3.googleusercontent.com/-eeqi67Zx_BI/AAAAAAAAAAI/AAAAAAAABd4/u_OPuYGcU2E/photo.jpg?sz=128", "user_id": 7081597, "user_type": "registered", "link": "http://stackoverflow.com/users/7081597/jeyakeethan-geethan"}, "link": "http://stackoverflow.com/questions/40290400/casting-of-joined-list-of-integers-to-int-throws-valueerror-in-python", "tags": ["python"], "creation_date": 1477587749, "score": -1, "closed_date": 1477589661, "last_edit_date": 1477671371, "is_answered": false, "view_count": 43, "last_activity_date": 1477671371, "question_id": 40290400, "closed_reason": "off-topic", "answer_count": 2, "title": "Casting of joined list of integers to int throws ValueError in Python"}