{"last_activity_date": 1477754130, "owner": {"display_name": "lucapozzobon", "reputation": 53, "profile_image": "https://www.gravatar.com/avatar/b491e81ef21739cfc487cdd067a3fc21?s=128&d=identicon&r=PG", "user_id": 2581400, "user_type": "registered", "accept_rate": 50, "link": "http://stackoverflow.com/users/2581400/lucapozzobon"}, "is_answered": true, "answer_count": 1, "creation_date": 1477753683, "score": -1, "title": "Python conflict with keyword &quot;from&quot; in telegram bot", "tags": ["python", "telegram-bot", "python-telegram-bot"], "view_count": 19, "question_id": 40320467, "link": "http://stackoverflow.com/questions/40320467/python-conflict-with-keyword-from-in-telegram-bot"}