{"owner": {"display_name": "harvey_slash", "reputation": 2780, "profile_image": "https://i.stack.imgur.com/D7vOJ.jpg?s=128&g=1", "user_id": 2670775, "user_type": "registered", "accept_rate": 47, "link": "http://stackoverflow.com/users/2670775/harvey-slash"}, "link": "http://stackoverflow.com/questions/40325994/runtimeerror-attempted-to-use-a-closed-session", "tags": ["python", "ssh", "debian", "tensorflow"], "creation_date": 1477801142, "score": 0, "last_edit_date": 1477840020, "is_answered": false, "view_count": 95, "last_activity_date": 1477840020, "question_id": 40325994, "answer_count": 0, "title": "RuntimeError: Attempted to use a closed Session"}